### ISSUE TITLE
Addon no longer works

### ISSUE THREAD

**Issue by xsmashx88x** [Echological/MentionChannels-BD#5]
i have installed few more addons, and seems this has stopped working. Have you heard of others having issues with this and other addons?

**Comment by Echological** [comment]
could you explain a little more, because this plugin doesn't have much extension that could be intercepted and interfered by other plugins.

it seems to work well with me, i do have a large amount of plugins installed so i don't think it's a majority problem

**Comment by XxUnkn0wnxX** [comment]
@Echological This has been dead since the big Discord Update
There is no Mentions Button
![Screen Shot 2022-01-15 at 10 40 04 am](https://user-images.githubusercontent.com/2242880/149598665-cfa1a7fb-33f1-4430-804e-f8d7da1e45d4.jpg)
![Screen Shot 2022-01-15 at 10 40 14 am](https://user-images.githubusercontent.com/2242880/149598667-a3589dc5-65d7-4b48-bebd-47a2cf9a6896.jpg)
[debug.log](https://github.com/Echological/MentionChannels-BD/files/7873805/debug.log)
![Screen Shot 2022-01-15 at 10 42 55 am](https://user-images.githubusercontent.com/2242880/149598809-1a589fe8-62ac-4737-9d74-5ea309111959.jpg)

**Comment by Echological** [comment]
> @Echological This has been dead since the big Discord Update There is no Mentions Button ![Screen Shot 2022-01-15 at 10 40 04 am](https://user-images.githubusercontent.com/2242880/149598665-cfa1a7fb-33f1-4430-804e-f8d7da1e45d4.jpg) ![Screen Shot 2022-01-15 at 10 40 14 am](https://user-images.githubusercontent.com/2242880/149598667-a3589dc5-65d7-4b48-bebd-47a2cf9a6896.jpg) [debug.log](https://github.com/Echological/MentionChannels-BD/files/7873805/debug.log) ![Screen Shot 2022-01-15 at 10 42 55 am](https://user-images.githubusercontent.com/2242880/149598809-1a589fe8-62ac-4737-9d74-5ea309111959.jpg)

I made a new issue for your concern, rather than addressing it within a dead issue. Please refer to #6.
